### ISSUE TITLE
批量请求和链式请求是啥意思啊？还是没看懂，求详解

### ISSUE THREAD

**Issue by ganjmeng** [DaZuo/DZRequest#1]
批量请求和链式请求是啥意思啊？还是没看懂，求详解

**Comment by ganjmeng** [comment]
大神代码写的好好

**Comment by ganjmeng** [comment]
刚刚仔细看了一下，太牛逼了

**Comment by ganjmeng** [comment]
还收徒吗。。

**Comment by wenbingzuo** [comment]
@ganjmeng 批量嘛，就是多个请求，各个请求之前没有太多联系。链式嘛一般是一个请求依赖于前一个请求。不过这两种请求都可以用单个的请求来完成，只不过逻辑被提前弄好了，不用在单个写逻辑了

**Comment by wenbingzuo** [comment]
@ganjmeng 话说你是群里的人么？^_^

**Comment by ganjmeng** [comment]
什么群啊，拉我进组织啊，QQ178153955

**Comment by wenbingzuo** [comment]
@ganjmeng 272981646群号，人少
